# 🎬 Movie Data Analysis using Python

## A Data Cleaning and Exploratory Data Analysis Project

**Prepared by:** Hariharan A

**Department:** Computer Science and Engineering

**Institution:** Bharath Institute of Higher Education and Research

**Tools Used**
- Python
- Pandas
- NumPy
- Jupyter Notebook

**Dataset**
Movie Assignment Dataset

---

# Project Overview

This project focuses on analyzing a movie dataset using Python. The objective is to clean the dataset, handle missing values, remove irrelevant information, and perform exploratory data analysis (EDA) to extract meaningful insights about movie profitability, ratings, directors, genres, and actors.

The project demonstrates practical applications of Pandas and NumPy for real-world data analysis tasks.

# Project Objectives

The objectives of this project are:

- Read and inspect the movie dataset.
- Analyze the structure of the dataset.
- Handle missing values.
- Remove unnecessary columns.
- Remove duplicate records.
- Calculate movie profits.
- Identify the highest profitable movies.
- Find IMDb Top 250 movies.
- Analyze top-rated directors.
- Study genre popularity.
- Compare audience and critic preferences for actors.

# Step 1: Import Required Libraries

## Objective

The first step of every data analysis project is importing the necessary Python libraries. These libraries provide functions for handling datasets, performing numerical computations, and suppressing unnecessary warning messages.

The following libraries are used:

- **Pandas** for data manipulation.
- **NumPy** for numerical operations.
- **Warnings** to suppress unwanted warning messages.

In [2]:
# Supress Warnings

import warnings
warnings.filterwarnings('ignore')

# Import the numpy and pandas packages

import numpy as np
import pandas as pd

# Step 2: Import the Dataset

## Objective

The movie dataset is stored in CSV format. In this step, the dataset is imported into a Pandas DataFrame named **movies**. This DataFrame will be used throughout the project for data cleaning and analysis.

In [4]:
movies = pd.read_csv('Movie+Assignment+Data.csv')

movies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456


## Determine Dataset Dimensions

The shape of the dataset is checked to determine the total number of observations (rows) and attributes (columns).

## Examine Dataset Information

The information of the dataset is displayed to understand:

- Total number of records
- Number of columns
- Data types
- Missing values
- Memory usage

In [5]:
print(movies.shape)
print(movies.info())

(5043, 28)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5022 non-null   float64
 19  language                   5029 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB
None

# Step 3: Missing Value Analysis

## Objective

Real-world datasets usually contain incomplete information. This step identifies missing values present in each column and calculates the percentage of missing records.

This information helps determine the most appropriate data cleaning strategy.

In [6]:
movies.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      14
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [7]:
movies.isnull().sum(axis=1)

0        0
1        0
2        0
3        0
4       14
        ..
5038     4
5039     5
5040     4
5041     2
5042     0
Length: 5043, dtype: int64

In [8]:
null_percentage = (movies.isnull().sum() / len(movies)) * 100
null_percentage_rounded = null_percentage.round(2)
null_percentage_rounded

color                         0.38
director_name                 2.06
num_critic_for_reviews        0.99
duration                      0.30
director_facebook_likes       2.06
actor_3_facebook_likes        0.46
actor_2_name                  0.26
actor_1_facebook_likes        0.14
gross                        17.53
genres                        0.00
actor_1_name                  0.14
movie_title                   0.00
num_voted_users               0.00
cast_total_facebook_likes     0.00
actor_3_name                  0.46
facenumber_in_poster          0.26
plot_keywords                 3.03
movie_imdb_link               0.00
num_user_for_reviews          0.42
language                      0.28
country                       0.10
content_rating                6.01
budget                        9.76
title_year                    2.14
actor_2_facebook_likes        0.26
imdb_score                    0.00
aspect_ratio                  6.52
movie_facebook_likes          0.00
dtype: float64

# Step 4: Remove Unnecessary Columns

## Objective

Several columns are not relevant to the objectives of this project. These columns are removed to simplify the dataset and improve processing efficiency.

Removing unnecessary features also reduces memory usage and improves readability.

In [9]:
movies = movies.drop(['color', 
                      'director_facebook_likes', 
                      'actor_3_facebook_likes', 
                      'actor_1_facebook_likes', 
                      'cast_total_facebook_likes', 
                      'actor_2_facebook_likes', 
                      'duration', 
                      'facenumber_in_poster', 
                      'content_rating', 
                      'country', 
                      'movie_imdb_link', 
                      'aspect_ratio',
                      'plot_keywords',
                      'actor_2_name',
                      'actor_3_name'], 
                       axis = 1)
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
4,Doug Walker,NaN,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,NaN,NaN,NaN,NaN,7.1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Scott Smith,1.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,6.0,English,NaN,2013.0,7.7,84
5039,NaN,43.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,359.0,English,NaN,NaN,7.5,32000
5040,Benjamin Roberds,13.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,3.0,English,1400.0,2013.0,6.3,16
5041,Daniel Hsia,14.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,9.0,English,NaN,2012.0,6.3,660
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456

# Step 5: Remove Incomplete Records

## Objective

Rows containing excessive missing values are removed because they provide limited analytical value and may affect the accuracy of the analysis.

In [10]:
null_percentage = (movies.isnull().sum() / len(movies)) * 100
columns_drop = null_percentage[null_percentage > 5].index.tolist()
movies_cleaned_1 = movies.dropna(subset=columns_drop)
movies_cleaned_1

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,424760.0,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,7000.0,2004.0,7.0,19000
5034,Neill Dela Llana,35.0,70071.0,Thriller,Ian Gamazon,Cavite,589,35.0,English,7000.0,2005.0,6.3,74
5035,Robert Rodriguez,56.0,2040920.0,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,7000.0,1992.0,6.9,0
5037,Edward Burns,14.0,4584.0,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14.0,English,9000.0,2011.0,6.4,413
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456

In [11]:
movies_cleaned_2 = movies_cleaned_1.dropna(thresh = 8)
movies_cleaned_2

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,424760.0,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,7000.0,2004.0,7.0,19000
5034,Neill Dela Llana,35.0,70071.0,Thriller,Ian Gamazon,Cavite,589,35.0,English,7000.0,2005.0,6.3,74
5035,Robert Rodriguez,56.0,2040920.0,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,7000.0,1992.0,6.9,0
5037,Edward Burns,14.0,4584.0,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14.0,English,9000.0,2011.0,6.4,413
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456

# Step 6: Handle Remaining Missing Values

## Objective

Some missing values remain after removing incomplete records. Since English is the dominant language in the dataset, missing values in the language column are replaced with "English".

In [12]:
movies_cleaned_2['language'] = movies_cleaned_2['language'].fillna('English')
movies_cleaned_2

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,424760.0,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,7000.0,2004.0,7.0,19000
5034,Neill Dela Llana,35.0,70071.0,Thriller,Ian Gamazon,Cavite,589,35.0,English,7000.0,2005.0,6.3,74
5035,Robert Rodriguez,56.0,2040920.0,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,7000.0,1992.0,6.9,0
5037,Edward Burns,14.0,4584.0,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14.0,English,9000.0,2011.0,6.4,413
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456

# Step 7: Verify the Cleaned Dataset

## Objective

After completing the cleaning process, the percentage of retained records is calculated. This helps evaluate how much useful information remains for analysis.

In [13]:
total_rows = movies.shape[0]
retained_rows = movies_cleaned_2.shape[0]
percentage_retained = (retained_rows / total_rows) * 100
percentage_retained

77.15645449137418

# Step 8: Convert Financial Units

## Objective

The budget and gross revenue values are converted from dollars to millions of dollars to make the values easier to interpret and compare.

In [14]:
movies_cleaned_2['budget'] = movies_cleaned_2['budget'] / 1_000_000 
movies_cleaned_2['gross'] = movies_cleaned_2['gross'] / 1_000_000  
movies_cleaned_2

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0000,2009.0,7.9,33000
1,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300.0000,2007.0,7.1,0
2,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245.0000,2015.0,6.8,85000
3,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250.0000,2012.0,8.5,164000
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.7000,2012.0,6.6,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,0.424760,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,0.0070,2004.0,7.0,19000
5034,Neill Dela Llana,35.0,0.070071,Thriller,Ian Gamazon,Cavite,589,35.0,English,0.0070,2005.0,6.3,74
5035,Robert Rodriguez,56.0,2.040920,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,0.0070,1992.0,6.9,0
5037,Edward Burns,14.0,0.004584,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14.0,English,0.0090,2011.0,6.4,413
5042,Jon Gunn,43.0,0.085222,Documentary,John August,My Date with Drew,4285,84.0,English,0.0011,2004.0,6.6,456

# Step 9: Profit Analysis

## Objective

Movie profitability is calculated by subtracting the production budget from the gross revenue.

The calculated profit is stored as a new feature for further analysis.

In [15]:
movies_cleaned_2['profit'] = movies_cleaned_2['gross'] - movies_cleaned_2['budget']
print(movies_cleaned_2[['budget', 'gross', 'profit']])

        budget       gross      profit
0     237.0000  760.505847  523.505847
1     300.0000  309.404152    9.404152
2     245.0000  200.074175  -44.925825
3     250.0000  448.130642  198.130642
5     263.7000   73.058679 -190.641321
...        ...         ...         ...
5033    0.0070    0.424760    0.417760
5034    0.0070    0.070071    0.063071
5035    0.0070    2.040920    2.033920
5037    0.0090    0.004584   -0.004416
5042    0.0011    0.085222    0.084122

[3891 rows x 3 columns]

## Identify the Most Profitable Movies

The movies are sorted according to profit in descending order to identify the highest profitable movies in the dataset.

In [16]:
sorted_movies = movies_cleaned_2.sort_values(by='profit', ascending=False)

sorted_movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.000000,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.000000,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.000000,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.000000,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.500000,1982.0,7.9,34000,424.449459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2334,Katsuhiro Ôtomo,105.0,0.410388,Action|Adventure|Animation|Family|Sci-Fi|Thriller,William Hootkins,Steamboy,13727,79.0,Japanese,2127.519898,2004.0,6.9,973,-2127.109510
2323,Hayao Miyazaki,174.0,2.298191,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2400.000000,1997.0,8.4,11000,-2397.701809
3005,Lajos Koltai,73.0,0.195888,Drama|Romance|War,Marcell Nagy,Fateless,5603,45.0,Hungarian,2500.000000,2005.0,7.1,607,-2499.804112
3859,Chan-wook Park,202.0,0.211667,Crime|Drama,Min-sik Choi,Lady Vengeance,53508,131.0,Korean,4200.000000,2005.0,7.7,4000,-4199.788333
2988,Joon-ho Bong,363.0,2.201412,Comedy|Drama|Horror|Sci-Fi,Doona Bae,The Host,68883,279.0,Korean,12215.500000,2006.0,7.0,7000,-12213.298588

In [17]:
top10 = movies.iloc[:10, ]
top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
4,Doug Walker,NaN,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,NaN,NaN,NaN,NaN,7.1,0
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000
6,Sam Raimi,392.0,336530303.0,Action|Adventure|Romance,J.K. Simmons,Spider-Man 3,383056,1902.0,English,258000000.0,2007.0,6.2,0
7,Nathan Greno,324.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,Brad Garrett,Tangled,294810,387.0,English,260000000.0,2010.0,7.8,29000
8,Joss Whedon,635.0,458991599.0,Action|Adventure|Sci-Fi,Chris Hemsworth,Avengers: Age of Ultron,462669,1117.0,English,250000000.0,2015.0,7.5,118000
9,David Yates,375.0,301956980.0,Adventure|Family|Fantasy|Mystery,Alan Rickman,Harry Potter and the Half-Blood Prince,321795,973.0,English,250000000.0,2009.0,7.5,10000

# Step 10: Remove Duplicate Records

## Objective

Duplicate records are removed to eliminate redundant observations and improve the reliability of the analysis.

In [18]:
movies.drop_duplicates(subset = None, keep = 'first', inplace = True)
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
4,Doug Walker,NaN,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,NaN,NaN,NaN,NaN,7.1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Scott Smith,1.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,6.0,English,NaN,2013.0,7.7,84
5039,NaN,43.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,359.0,English,NaN,NaN,7.5,32000
5040,Benjamin Roberds,13.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,3.0,English,1400.0,2013.0,6.3,16
5041,Daniel Hsia,14.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,9.0,English,NaN,2012.0,6.3,660
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456

In [19]:
movies_cleaned_2['profit'] = movies_cleaned_2['gross'] - movies_cleaned_2['budget']

sorted_movies = movies_cleaned_2.sort_values(by='profit', ascending=False)
top10 = sorted_movies.head(10)
top10 = top10.drop_duplicates()
top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.5,1982.0,7.9,34000,424.449459
17,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
509,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.0,1994.0,8.5,17000,377.783777
240,George Lucas,320.0,474.544677,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.0,1999.0,6.5,13000,359.544677
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.316061

# Step 11: IMDb Top 250 Analysis

## Objective

Movies are filtered based on IMDb score and user votes to identify the highest-rated movies.

Only movies with more than **25,000 user votes** are considered to ensure ranking reliability.

In [20]:
IMDb_Top_250 = movies.sort_values(by = 'imdb_score', ascending = False)
IMDb_Top_250 = IMDb_Top_250.loc[IMDb_Top_250.num_voted_users > 25000]
IMDb_Top_250 = IMDb_Top_250.iloc[:250, ]
IMDb_Top_250['Rank'] = range(1,251)
IMDb_Top_250

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Rank
1937,Frank Darabont,199.0,28341469.0,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144.0,English,25000000.0,1994.0,9.3,108000,1
3466,Francis Ford Coppola,208.0,134821952.0,Crime|Drama,Al Pacino,The Godfather,1155770,2238.0,English,6000000.0,1972.0,9.2,43000,2
2837,Francis Ford Coppola,149.0,57300000.0,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650.0,English,13000000.0,1974.0,9.0,14000,3
3481,NaN,54.0,NaN,Crime|Drama|Thriller,Kirsten Dunst,Fargo,170055,173.0,English,NaN,NaN,9.0,61000,4
66,Christopher Nolan,645.0,533316061.0,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185000000.0,2008.0,9.0,37000,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2937,Franklin J. Schaffner,112.0,NaN,Biography|Drama|War,George C. Scott,Patton,76398,258.0,English,12000000.0,1970.0,8.0,0,246
3821,Billy Bob Thornton,104.0,24475416.0,Drama,Robert Duvall,Sling Blade,72443,309.0,English,890000.0,1996.0,8.0,0,247
2944,Martin Campbell,400.0,167007184.0,Action|Adventure|Thriller,Eva Green,Casino Royale,470501,2301.0,English,150000000.0,2006.0,8.0,0,248
3280,Norman Jewison,66.0,50000000.0,Drama|Family|Musical|Romance,Topol,Fiddler on the Roof,29839,150.0,English,9000000.0,1971.0,8.0,0,249
3741,Edgar Wright,246.0,13464388.0,Comedy|Horror,Peter Serafinowicz,Shaun of the Dead,395921,859.0,English,4000000.0,2004.0,8.0,19000,250

In [21]:
Top_Foreign_Lang_Film =IMDb_Top_250.loc[IMDb_Top_250['language'] != 'English']
Top_Foreign_Lang_Film

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Rank
4498,Sergio Leone,181.0,6100000.0,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.200000e+06,1966.0,8.9,20000,8
4747,Akira Kurosawa,153.0,269061.0,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596.0,Japanese,2.000000e+06,1954.0,8.7,11000,23
4029,Fernando Meirelles,214.0,7563397.0,Crime|Drama,Alice Braga,City of God,533200,749.0,Portuguese,3.300000e+06,2002.0,8.7,28000,25
2373,Hayao Miyazaki,246.0,10049886.0,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902.0,Japanese,1.900000e+07,2001.0,8.6,28000,38
4921,Majid Majidi,46.0,925402.0,Drama|Family,Bahare Seddiqi,Children of Heaven,27882,130.0,Persian,1.800000e+05,1997.0,8.5,0,40
3870,Raja Menon,39.0,NaN,Action|Drama|History|Thriller|War,Nimrat Kaur,Airlift,30977,178.0,Hindi,4.400000e+06,2016.0,8.5,10000,46
4259,Florian Henckel von Donnersmarck,215.0,11284657.0,Drama|Thriller,Sebastian Koch,The Lives of Others,259379,407.0,German,2.000000e+06,2006.0,8.5,39000,52
1298,Jean-Pierre Jeunet,242.0,33201661.0,Comedy|Romance,Mathieu Kassovitz,Amélie,534262,1314.0,French,7.700000e+07,2001.0,8.4,39000,62
4105,Chan-wook Park,305.0,2181290.0,Drama|Mystery|Thriller,Min-sik Choi,Oldboy,356181,809.0,Korean,3.000000e+06,2003.0,8.4,43000,63
2323,Hayao Miyazaki,174.0,2298191.0,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2.400000e+09,1997.0,8.4,11000,65
2970,Wolfgang Petersen,96.0,11433134.0,Adventure|Drama|Thriller|War,Jürgen Prochnow,Das Boot,168203,426.0,German,1.400000e+07,1981.0,8.4,11000,67
4659,Asghar Farhadi,354.0,7098492.0,Drama|Mystery,Shahab Hosseini,A Separation,151812,264.0,Persian,5.000000e+05,2011.0,8.4,48000,73
1329,S.S. Rajamouli,44.0,6498000.0,Action|Adventure|Drama|Fantasy|War,Tamannaah Bhatia,Baahubali: The Beginning,62756,410.0,Telugu,1.802615e+07,2015.0,8.4,21000,76
3685,Rakeysh Omprakash Mehra,33.0,2197331.0,Comedy|Drama|History|Romance,Anupam Kher,Rang De Basanti,70233,321.0,Hindi,NaN,2006.0,8.4,0,84
2829,Oliver Hirschbiegel,192.0,5501940.0,Biography|Drama|History|War,Thomas Kretschmann,Downfall,248354,564.0,German,1.350000e+07,2004.0,8.3,14000,94
2734,Fritz Lang,260.0,26435.0,Drama|Sci-Fi,Brigitte Helm,Metropolis,111841,413.0,German,6.000000e+06,1927.0,8.3,12000,101
4033,Thomas Vinterberg,349.0,610968.0,Drama,Thomas Bo Larsen,The Hunt,170155,249.0,Danish,3.800000e+06,2012.0,8.3,60000,113
4160,Rajkumar Hirani,15.0,NaN,Comedy|Drama|Romance,Vidya Balan,Lage Raho Munna Bhai,27569,106.0,Hindi,1.200000e+08,2006.0,8.2,349,116
2047,Hayao Miyazaki,212.0,4710455.0,Adventure|Animation|Family|Fantasy,Christian Bale,Howl's Moving Castle,214091,330.0,Japanese,2.400000e+07,2004.0,8.2,13000,124
2551,Guillermo del Toro,406.0,37623143.0,Drama|Fantasy|War,Ivana Baquero,Pan's Labyrinth,467234,1083.0,Spanish,1.350000e+07,2006.0,8.2,27000,126
4000,Juan José Campanella,262.0,20167424.0,Drama|Mystery|Thriller,Ricardo Darín,The Secret in Their Eyes,131831,231.0,Spanish,2.000000e+06,2009.0,8.2,33000,127
3550,Denis Villeneuve,226.0,6857096.0,Drama|Mystery|War,Lubna Azabal,Incendies,80429,156.0,French,6.800000e+06,2010.0,8.2,37000,129
3553,José Padilha,142.0,8060.0,Action|Crime|Drama|Thriller,Wagner Moura,Elite Squad,81644,107.0,Portuguese,4.000000e+06,2007.0,8.1,11000,146
1061,Andrei Tarkovsky,144.0,NaN,Drama|Mystery|Sci-Fi,Donatas Banionis,Solaris,54057,236.0,Russian,1.000000e+06,1972.0,8.1,0,147
3423,Katsuhiro Ôtomo,150.0,439162.0,Action|Animation|Sci-Fi,Mitsuo Iwata,Akira,106160,430.0,Japanese,1.100000e+09,1988.0,8.1,0,148
2830,Alejandro Amenábar,157.0,2086345.0,Biography|Drama|Romance,Belén Rueda,The Sea Inside,64556,140.0,Spanish,1.000000e+07,2004.0,8.1,0,162
2914,Je-kyu Kang,86.0,1110186.0,Action|Drama|War,Min-sik Choi,Tae Guk Gi: The Brotherhood of War,31943,224.0,Korean,1.280000e+07,2004.0,8.1,0,176
4267,Alejandro G. Iñárritu,157.0,5383834.0,Drama|Thriller,Adriana Barraza,Amores Perros,173551,361.0,Spanish,2.000000e+06,2000.0,8.1,11000,187
4461,Thomas Vinterberg,98.0,1647780.0,Drama,Ulrich Thomsen,The Celebration,65951,258.0,Danish,1.300000e+06,1998.0,8.1,5000,196
3344,Karan Johar,210.0,4018695.0,Adventure|Drama|Thriller,Shah Rukh Khan,My Name Is Khan,69759,235.0,Hindi,1.200000e+07,2010.0,8.0,27000,202
3456,Vincent Paronnaud,242.0,4443403.0,Animation|Biography|Drama|War,Catherine Deneuve,Persepolis,70194,158.0,French,7.300000e+06,2007.0,8.0,14000,218
2802,Julian Schnabel,259.0,5990075.0,Biography|Drama,Emmanuelle Seigner,The Diving Bell and the Butterfly,89906,175.0,French,NaN,2007.0,8.0,13000,219
4284,Ari Folman,231.0,2283276.0,Animation|Biography|Documentary|Drama|History|War,Ari Folman,Waltz with Bashir,46107,156.0,Hebrew,1.500000e+06,2008.0,8.0,0,221
2739,Andrey Zvyagintsev,103.0,502028.0,Drama|Mystery|Thriller,Konstantin Lavronenko,The Return,31589,172.0,Russian,NaN,2003.0,8.0,0,241
4144,Walter Salles,71.0,5595428.0,Drama,Fernanda Montenegro,Central Station,28951,257.0,Portuguese,2.900000e+06,1998.0,8.0,0,242
4897,Sergio Leone,122.0,3500000.0,Action|Drama|Western,Clint Eastwood,A Fistful of Dollars,147566,235.0,Italian,2.000000e+05,1964.0,8.0,0,244

# Step 13: Director Performance Analysis

## Objective

The average IMDb score of each director is calculated to identify directors who consistently produce highly rated movies.

In [22]:
director = movies.pivot_table(values = 'imdb_score', index = 'director_name', aggfunc = 'mean')
director = director.sort_values(by = 'imdb_score', ascending = False)
director = director.iloc[:10, ]
director

                  imdb_score
director_name
John Blanchard           9.5
Sadyk Sher-Niyaz         8.7
Cary Bell                8.7
Mitchell Altieri         8.7
Mike Mayhall             8.6
Charles Chaplin          8.6
Damien Chazelle          8.5
Raja Menon               8.5
Majid Majidi             8.5
Ron Fricke               8.5

# Step 14: Genre Combination Analysis

## Objective

Many movies belong to multiple genres.

This analysis separates the primary and secondary genres and identifies genre combinations that generate the highest average gross revenue.

In [23]:
movies['genres'] = movies['genres'].str.split('|')
movies['genre_1'] = movies['genres'].apply(lambda x: x[0])
movies['genre_2'] = movies['genres'].apply(lambda x : x[1] if len(x) > 1 else x[0])
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,genre_1,genre_2
0,James Cameron,723.0,760505847.0,"[Action, Adventure, Fantasy, Sci-Fi]",CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000,Action,Adventure
1,Gore Verbinski,302.0,309404152.0,"[Action, Adventure, Fantasy]",Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0,Action,Adventure
2,Sam Mendes,602.0,200074175.0,"[Action, Adventure, Thriller]",Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000,Action,Adventure
3,Christopher Nolan,813.0,448130642.0,"[Action, Thriller]",Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000,Action,Thriller
4,Doug Walker,NaN,NaN,[Documentary],Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,NaN,NaN,NaN,NaN,7.1,0,Documentary,Documentary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Scott Smith,1.0,NaN,"[Comedy, Drama]",Eric Mabius,Signed Sealed Delivered,629,6.0,English,NaN,2013.0,7.7,84,Comedy,Drama
5039,NaN,43.0,NaN,"[Crime, Drama, Mystery, Thriller]",Natalie Zea,The Following,73839,359.0,English,NaN,NaN,7.5,32000,Crime,Drama
5040,Benjamin Roberds,13.0,NaN,"[Drama, Horror, Thriller]",Eva Boehnke,A Plague So Pleasant,38,3.0,English,1400.0,2013.0,6.3,16,Drama,Horror
5041,Daniel Hsia,14.0,10443.0,"[Comedy, Drama, Romance]",Alan Ruck,Shanghai Calling,1255,9.0,English,NaN,2012.0,6.3,660,Comedy,Drama
5042,Jon Gunn,43.0,85222.0,[Documentary],John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456,Documentary,Documentary

In [24]:
movies_by_segment =movies_by_segment = movies.groupby(['genre_1', 'genre_2'])

In [25]:
PopGenre = pd.DataFrame(movies_by_segment['gross'].mean()).sort_values(by = 'gross', ascending = False)
PopGenre.iloc[:5, ]

                            gross
genre_1   genre_2
Family    Sci-Fi     4.349495e+08
Adventure Sci-Fi     2.286278e+08
          Animation  1.170500e+08
          Family     1.155375e+08
Action    Adventure  1.087523e+08

# Step 15: Actor Popularity Analysis

## Objective

This analysis compares three well-known actors:

- Meryl Streep
- Leonardo DiCaprio
- Brad Pitt

The comparison is based on both critic reviews and user reviews to identify audience and critic preferences.

In [26]:
Meryl_Streep = movies.loc[movies.actor_1_name == 'Meryl Streep']
Meryl_Streep

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,genre_1,genre_2
410,Nancy Meyers,187.0,112703470.0,"[Comedy, Drama, Romance]",Meryl Streep,It's Complicated,69860,214.0,English,85000000.0,2009.0,6.6,0,Comedy,Drama
1106,Curtis Hanson,42.0,46815748.0,"[Action, Adventure, Crime, Thriller]",Meryl Streep,The River Wild,32544,69.0,English,45000000.0,1994.0,6.3,0,Action,Adventure
1204,Nora Ephron,252.0,94125426.0,"[Biography, Drama, Romance]",Meryl Streep,Julie & Julia,79264,277.0,English,40000000.0,2009.0,7.0,13000,Biography,Drama
1408,David Frankel,208.0,124732962.0,"[Comedy, Drama, Romance]",Meryl Streep,The Devil Wears Prada,286178,631.0,English,35000000.0,2006.0,6.8,0,Comedy,Drama
1483,Robert Redford,227.0,14998070.0,"[Drama, Thriller, War]",Meryl Streep,Lions for Lambs,41170,298.0,English,35000000.0,2007.0,6.2,0,Drama,Thriller
1575,Sydney Pollack,66.0,87100000.0,"[Biography, Drama, Romance]",Meryl Streep,Out of Africa,52339,200.0,English,31000000.0,1985.0,7.2,0,Biography,Drama
1618,David Frankel,234.0,63536011.0,"[Comedy, Drama, Romance]",Meryl Streep,Hope Springs,34258,178.0,English,30000000.0,2012.0,6.3,0,Comedy,Drama
1674,Carl Franklin,64.0,23209440.0,[Drama],Meryl Streep,One True Thing,9283,112.0,English,30000000.0,1998.0,7.0,592,Drama,Drama
1752,Stephen Frears,87.0,NaN,"[Biography, Comedy, Drama, Music, Romance]",Meryl Streep,Florence Foster Jenkins,2167,32.0,English,29000000.0,2016.0,7.1,0,Biography,Comedy
1925,Stephen Daldry,174.0,41597830.0,"[Drama, Romance]",Meryl Streep,The Hours,102123,660.0,English,25000000.0,2002.0,7.6,0,Drama,Romance
2781,Phyllida Lloyd,331.0,29959436.0,"[Biography, Drama, History]",Meryl Streep,The Iron Lady,82327,350.0,English,13000000.0,2011.0,6.4,18000,Biography,Drama
3135,Robert Altman,211.0,20338609.0,"[Comedy, Drama, Music]",Meryl Streep,A Prairie Home Companion,19655,280.0,English,10000000.0,2006.0,6.8,683,Comedy,Drama
3641,Fred Zinnemann,38.0,NaN,[Drama],Meryl Streep,Julia,6454,44.0,English,7840000.0,1977.0,7.4,733,Drama,Drama

In [27]:
Leo_Caprio = movies.loc[movies.actor_1_name == 'Leonardo DiCaprio']
Leo_Caprio

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,genre_1,genre_2
26,James Cameron,315.0,658672302.0,"[Drama, Romance]",Leonardo DiCaprio,Titanic,793059,2528.0,English,200000000.0,1997.0,7.7,26000,Drama,Romance
50,Baz Luhrmann,490.0,144812796.0,"[Drama, Romance]",Leonardo DiCaprio,The Great Gatsby,362912,753.0,English,105000000.0,2013.0,7.3,115000,Drama,Romance
97,Christopher Nolan,642.0,292568851.0,"[Action, Adventure, Sci-Fi, Thriller]",Leonardo DiCaprio,Inception,1468200,2803.0,English,160000000.0,2010.0,8.8,175000,Action,Adventure
179,Alejandro G. Iñárritu,556.0,183635922.0,"[Adventure, Drama, Thriller, Western]",Leonardo DiCaprio,The Revenant,406020,1188.0,English,135000000.0,2015.0,8.1,190000,Adventure,Drama
257,Martin Scorsese,267.0,102608827.0,"[Biography, Drama]",Leonardo DiCaprio,The Aviator,264318,799.0,English,110000000.0,2004.0,7.5,0,Biography,Drama
296,Quentin Tarantino,765.0,162804648.0,"[Drama, Western]",Leonardo DiCaprio,Django Unchained,955174,1193.0,English,100000000.0,2012.0,8.5,199000,Drama,Western
307,Edward Zwick,166.0,57366262.0,"[Adventure, Drama, Thriller]",Leonardo DiCaprio,Blood Diamond,400292,657.0,English,100000000.0,2006.0,8.0,14000,Adventure,Drama
308,Martin Scorsese,606.0,116866727.0,"[Biography, Comedy, Crime, Drama]",Leonardo DiCaprio,The Wolf of Wall Street,780588,1138.0,English,100000000.0,2013.0,8.2,138000,Biography,Comedy
326,Martin Scorsese,233.0,77679638.0,"[Crime, Drama]",Leonardo DiCaprio,Gangs of New York,314033,1166.0,English,100000000.0,2002.0,7.5,0,Crime,Drama
361,Martin Scorsese,352.0,132373442.0,"[Crime, Drama, Thriller]",Leonardo DiCaprio,The Departed,873649,2054.0,English,90000000.0,2006.0,8.5,29000,Crime,Drama
452,Martin Scorsese,490.0,127968405.0,"[Mystery, Thriller]",Leonardo DiCaprio,Shutter Island,786092,964.0,English,80000000.0,2010.0,8.1,53000,Mystery,Thriller
641,Ridley Scott,238.0,39380442.0,"[Action, Drama, Thriller]",Leonardo DiCaprio,Body of Lies,174248,263.0,English,70000000.0,2008.0,7.1,0,Action,Drama
911,Steven Spielberg,194.0,164435221.0,"[Biography, Crime, Drama]",Leonardo DiCaprio,Catch Me If You Can,525801,667.0,English,52000000.0,2002.0,8.0,15000,Biography,Crime
990,Danny Boyle,118.0,39778599.0,"[Adventure, Drama, Thriller]",Leonardo DiCaprio,The Beach,176169,548.0,English,50000000.0,2000.0,6.6,0,Adventure,Drama
1114,Sam Mendes,323.0,22877808.0,"[Drama, Romance]",Leonardo DiCaprio,Revolutionary Road,152591,414.0,English,35000000.0,2008.0,7.3,0,Drama,Romance
1422,Randall Wallace,83.0,56876365.0,"[Action, Adventure]",Leonardo DiCaprio,The Man in the Iron Mask,125219,244.0,English,35000000.0,1998.0,6.4,0,Action,Adventure
1453,Clint Eastwood,392.0,37304950.0,"[Biography, Crime, Drama]",Leonardo DiCaprio,J. Edgar,102728,279.0,English,35000000.0,2011.0,6.6,16000,Biography,Crime
1560,Sam Raimi,63.0,18636537.0,"[Action, Thriller, Western]",Leonardo DiCaprio,The Quick and the Dead,69197,216.0,English,32000000.0,1995.0,6.4,0,Action,Thriller
2067,Jerry Zaks,45.0,12782508.0,[Drama],Leonardo DiCaprio,Marvin's Room,20163,71.0,English,23000000.0,1996.0,6.7,1000,Drama,Drama
2757,Baz Luhrmann,106.0,46338728.0,"[Drama, Romance]",Leonardo DiCaprio,Romeo + Juliet,167750,506.0,English,14500000.0,1996.0,6.8,10000,Drama,Romance
3476,Baz Luhrmann,490.0,144812796.0,"[Drama, Romance]",Leonardo DiCaprio,The Great Gatsby,362933,753.0,English,105000000.0,2013.0,7.3,115000,Drama,Romance

In [28]:
Brad_Pitt =movies.loc[movies.actor_1_name == 'Brad Pitt']
Brad_Pitt

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,genre_1,genre_2
101,David Fincher,362.0,127490802.0,"[Drama, Fantasy, Romance]",Brad Pitt,The Curious Case of Benjamin Button,459346,822.0,English,150000000.0,2008.0,7.8,23000,Drama,Fantasy
147,Wolfgang Petersen,220.0,133228348.0,[Adventure],Brad Pitt,Troy,381672,1694.0,English,175000000.0,2004.0,7.2,0,Adventure,Adventure
254,Steven Soderbergh,198.0,125531634.0,"[Crime, Thriller]",Brad Pitt,Ocean's Twelve,284852,627.0,English,110000000.0,2004.0,6.4,0,Crime,Thriller
255,Doug Liman,233.0,186336103.0,"[Action, Comedy, Crime, Romance, Thriller]",Brad Pitt,Mr. & Mrs. Smith,348861,798.0,English,120000000.0,2005.0,6.5,0,Action,Comedy
382,Tony Scott,142.0,26871.0,"[Action, Crime, Thriller]",Brad Pitt,Spy Game,121259,361.0,English,92000000.0,2001.0,7.0,0,Action,Crime
400,Steven Soderbergh,186.0,183405771.0,"[Crime, Thriller]",Brad Pitt,Ocean's Eleven,402645,845.0,English,85000000.0,2001.0,7.8,0,Crime,Thriller
470,David Ayer,406.0,85707116.0,"[Action, Drama, War]",Brad Pitt,Fury,303185,701.0,English,68000000.0,2014.0,7.6,82000,Action,Drama
611,Jean-Jacques Annaud,76.0,37901509.0,"[Adventure, Biography, Drama, History, War]",Brad Pitt,Seven Years in Tibet,96385,119.0,English,70000000.0,1997.0,7.0,0,Adventure,Biography
683,David Fincher,315.0,37023395.0,[Drama],Brad Pitt,Fight Club,1347461,2968.0,English,63000000.0,1999.0,8.8,48000,Drama,Drama
792,Patrick Gilmore,98.0,26288320.0,"[Adventure, Animation, Comedy, Drama, Family, ...",Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91.0,English,60000000.0,2003.0,6.7,880,Adventure,Animation
940,Neil Jordan,120.0,105264608.0,"[Drama, Fantasy, Horror]",Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406.0,English,60000000.0,1994.0,7.6,11000,Drama,Fantasy
1490,Terrence Malick,584.0,13303319.0,"[Drama, Fantasy]",Brad Pitt,The Tree of Life,136367,975.0,English,32000000.0,2011.0,6.7,39000,Drama,Fantasy
1722,Andrew Dominik,273.0,3904982.0,"[Biography, Crime, Drama, History, Western]",Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415.0,English,30000000.0,2007.0,7.5,0,Biography,Crime
2204,Alejandro G. Iñárritu,285.0,34300771.0,[Drama],Brad Pitt,Babel,243799,908.0,English,25000000.0,2006.0,7.5,0,Drama,Drama
2333,Angelina Jolie Pitt,131.0,531009.0,"[Drama, Romance]",Brad Pitt,By the Sea,7976,61.0,English,10000000.0,2015.0,5.3,0,Drama,Romance
2682,Andrew Dominik,414.0,14938570.0,"[Crime, Thriller]",Brad Pitt,Killing Them Softly,111625,369.0,English,15000000.0,2012.0,6.2,20000,Crime,Thriller
2898,Tony Scott,122.0,12281500.0,"[Action, Crime, Drama, Romance, Thriller]",Brad Pitt,True Romance,163492,460.0,English,13000000.0,1993.0,8.0,15000,Action,Crime
4749,Tom DiCillo,10.0,NaN,"[Comedy, Music, Romance]",Brad Pitt,Johnny Suede,3013,24.0,English,500000.0,1991.0,5.8,344,Comedy,Music

In [29]:
Combined = pd.concat([Meryl_Streep, Brad_Pitt, Leo_Caprio])
Combined

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,genre_1,genre_2
410,Nancy Meyers,187.0,112703470.0,"[Comedy, Drama, Romance]",Meryl Streep,It's Complicated,69860,214.0,English,85000000.0,2009.0,6.6,0,Comedy,Drama
1106,Curtis Hanson,42.0,46815748.0,"[Action, Adventure, Crime, Thriller]",Meryl Streep,The River Wild,32544,69.0,English,45000000.0,1994.0,6.3,0,Action,Adventure
1204,Nora Ephron,252.0,94125426.0,"[Biography, Drama, Romance]",Meryl Streep,Julie & Julia,79264,277.0,English,40000000.0,2009.0,7.0,13000,Biography,Drama
1408,David Frankel,208.0,124732962.0,"[Comedy, Drama, Romance]",Meryl Streep,The Devil Wears Prada,286178,631.0,English,35000000.0,2006.0,6.8,0,Comedy,Drama
1483,Robert Redford,227.0,14998070.0,"[Drama, Thriller, War]",Meryl Streep,Lions for Lambs,41170,298.0,English,35000000.0,2007.0,6.2,0,Drama,Thriller
1575,Sydney Pollack,66.0,87100000.0,"[Biography, Drama, Romance]",Meryl Streep,Out of Africa,52339,200.0,English,31000000.0,1985.0,7.2,0,Biography,Drama
1618,David Frankel,234.0,63536011.0,"[Comedy, Drama, Romance]",Meryl Streep,Hope Springs,34258,178.0,English,30000000.0,2012.0,6.3,0,Comedy,Drama
1674,Carl Franklin,64.0,23209440.0,[Drama],Meryl Streep,One True Thing,9283,112.0,English,30000000.0,1998.0,7.0,592,Drama,Drama
1752,Stephen Frears,87.0,NaN,"[Biography, Comedy, Drama, Music, Romance]",Meryl Streep,Florence Foster Jenkins,2167,32.0,English,29000000.0,2016.0,7.1,0,Biography,Comedy
1925,Stephen Daldry,174.0,41597830.0,"[Drama, Romance]",Meryl Streep,The Hours,102123,660.0,English,25000000.0,2002.0,7.6,0,Drama,Romance
2781,Phyllida Lloyd,331.0,29959436.0,"[Biography, Drama, History]",Meryl Streep,The Iron Lady,82327,350.0,English,13000000.0,2011.0,6.4,18000,Biography,Drama
3135,Robert Altman,211.0,20338609.0,"[Comedy, Drama, Music]",Meryl Streep,A Prairie Home Companion,19655,280.0,English,10000000.0,2006.0,6.8,683,Comedy,Drama
3641,Fred Zinnemann,38.0,NaN,[Drama],Meryl Streep,Julia,6454,44.0,English,7840000.0,1977.0,7.4,733,Drama,Drama
101,David Fincher,362.0,127490802.0,"[Drama, Fantasy, Romance]",Brad Pitt,The Curious Case of Benjamin Button,459346,822.0,English,150000000.0,2008.0,7.8,23000,Drama,Fantasy
147,Wolfgang Petersen,220.0,133228348.0,[Adventure],Brad Pitt,Troy,381672,1694.0,English,175000000.0,2004.0,7.2,0,Adventure,Adventure
254,Steven Soderbergh,198.0,125531634.0,"[Crime, Thriller]",Brad Pitt,Ocean's Twelve,284852,627.0,English,110000000.0,2004.0,6.4,0,Crime,Thriller
255,Doug Liman,233.0,186336103.0,"[Action, Comedy, Crime, Romance, Thriller]",Brad Pitt,Mr. & Mrs. Smith,348861,798.0,English,120000000.0,2005.0,6.5,0,Action,Comedy
382,Tony Scott,142.0,26871.0,"[Action, Crime, Thriller]",Brad Pitt,Spy Game,121259,361.0,English,92000000.0,2001.0,7.0,0,Action,Crime
400,Steven Soderbergh,186.0,183405771.0,"[Crime, Thriller]",Brad Pitt,Ocean's Eleven,402645,845.0,English,85000000.0,2001.0,7.8,0,Crime,Thriller
470,David Ayer,406.0,85707116.0,"[Action, Drama, War]",Brad Pitt,Fury,303185,701.0,English,68000000.0,2014.0,7.6,82000,Action,Drama
611,Jean-Jacques Annaud,76.0,37901509.0,"[Adventure, Biography, Drama, History, War]",Brad Pitt,Seven Years in Tibet,96385,119.0,English,70000000.0,1997.0,7.0,0,Adventure,Biography
683,David Fincher,315.0,37023395.0,[Drama],Brad Pitt,Fight Club,1347461,2968.0,English,63000000.0,1999.0,8.8,48000,Drama,Drama
792,Patrick Gilmore,98.0,26288320.0,"[Adventure, Animation, Comedy, Drama, Family, ...",Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91.0,English,60000000.0,2003.0,6.7,880,Adventure,Animation
940,Neil Jordan,120.0,105264608.0,"[Drama, Fantasy, Horror]",Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406.0,English,60000000.0,1994.0,7.6,11000,Drama,Fantasy
1490,Terrence Malick,584.0,13303319.0,"[Drama, Fantasy]",Brad Pitt,The Tree of Life,136367,975.0,English,32000000.0,2011.0,6.7,39000,Drama,Fantasy
1722,Andrew Dominik,273.0,3904982.0,"[Biography, Crime, Drama, History, Western]",Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415.0,English,30000000.0,2007.0,7.5,0,Biography,Crime
2204,Alejandro G. Iñárritu,285.0,34300771.0,[Drama],Brad Pitt,Babel,243799,908.0,English,25000000.0,2006.0,7.5,0,Drama,Drama
2333,Angelina Jolie Pitt,131.0,531009.0,"[Drama, Romance]",Brad Pitt,By the Sea,7976,61.0,English,10000000.0,2015.0,5.3,0,Drama,Romance
2682,Andrew Dominik,414.0,14938570.0,"[Crime, Thriller]",Brad Pitt,Killing Them Softly,111625,369.0,English,15000000.0,2012.0,6.2,20000,Crime,Thriller
2898,Tony Scott,122.0,12281500.0,"[Action, Crime, Drama, Romance, Thriller]",Brad Pitt,True Romance,163492,460.0,English,13000000.0,1993.0,8.0,15000,Action,Crime
4749,Tom DiCillo,10.0,NaN,"[Comedy, Music, Romance]",Brad Pitt,Johnny Suede,3013,24.0,English,500000.0,1991.0,5.8,344,Comedy,Music
26,James Cameron,315.0,658672302.0,"[Drama, Romance]",Leonardo DiCaprio,Titanic,793059,2528.0,English,200000000.0,1997.0,7.7,26000,Drama,Romance
50,Baz Luhrmann,490.0,144812796.0,"[Drama, Romance]",Leonardo DiCaprio,The Great Gatsby,362912,753.0,English,105000000.0,2013.0,7.3,115000,Drama,Romance
97,Christopher Nolan,642.0,292568851.0,"[Action, Adventure, Sci-Fi, Thriller]",Leonardo DiCaprio,Inception,1468200,2803.0,English,160000000.0,2010.0,8.8,175000,Action,Adventure
179,Alejandro G. Iñárritu,556.0,183635922.0,"[Adventure, Drama, Thriller, Western]",Leonardo DiCaprio,The Revenant,406020,1188.0,English,135000000.0,2015.0,8.1,190000,Adventure,Drama
257,Martin Scorsese,267.0,102608827.0,"[Biography, Drama]",Leonardo DiCaprio,The Aviator,264318,799.0,English,110000000.0,2004.0,7.5,0,Biography,Drama
296,Quentin Tarantino,765.0,162804648.0,"[Drama, Western]",Leonardo DiCaprio,Django Unchained,955174,1193.0,English,100000000.0,2012.0,8.5,199000,Drama,Western
307,Edward Zwick,166.0,57366262.0,"[Adventure, Drama, Thriller]",Leonardo DiCaprio,Blood Diamond,400292,657.0,English,100000000.0,2006.0,8.0,14000,Adventure,Drama
308,Martin Scorsese,606.0,116866727.0,"[Biography, Comedy, Crime, Drama]",Leonardo DiCaprio,The Wolf of Wall Street,780588,1138.0,English,100000000.0,2013.0,8.2,138000,Biography,Comedy
326,Martin Scorsese,233.0,77679638.0,"[Crime, Drama]",Leonardo DiCaprio,Gangs of New York,314033,1166.0,English,100000000.0,2002.0,7.5,0,Crime,Drama
361,Martin Scorsese,352.0,132373442.0,"[Crime, Drama, Thriller]",Leonardo DiCaprio,The Departed,873649,2054.0,English,90000000.0,2006.0,8.5,29000,Crime,Drama
452,Martin Scorsese,490.0,127968405.0,"[Mystery, Thriller]",Leonardo DiCaprio,Shutter Island,786092,964.0,English,80000000.0,2010.0,8.1,53000,Mystery,Thriller
641,Ridley Scott,238.0,39380442.0,"[Action, Drama, Thriller]",Leonardo DiCaprio,Body of Lies,174248,263.0,English,70000000.0,2008.0,7.1,0,Action,Drama
911,Steven Spielberg,194.0,164435221.0,"[Biography, Crime, Drama]",Leonardo DiCaprio,Catch Me If You Can,525801,667.0,English,52000000.0,2002.0,8.0,15000,Biography,Crime
990,Danny Boyle,118.0,39778599.0,"[Adventure, Drama, Thriller]",Leonardo DiCaprio,The Beach,176169,548.0,English,50000000.0,2000.0,6.6,0,Adventure,Drama
1114,Sam Mendes,323.0,22877808.0,"[Drama, Romance]",Leonardo DiCaprio,Revolutionary Road,152591,414.0,English,35000000.0,2008.0,7.3,0,Drama,Romance
1422,Randall Wallace,83.0,56876365.0,"[Action, Adventure]",Leonardo DiCaprio,The Man in the Iron Mask,125219,244.0,English,35000000.0,1998.0,6.4,0,Action,Adventure
1453,Clint Eastwood,392.0,37304950.0,"[Biography, Crime, Drama]",Leonardo DiCaprio,J. Edgar,102728,279.0,English,35000000.0,2011.0,6.6,16000,Biography,Crime
1560,Sam Raimi,63.0,18636537.0,"[Action, Thriller, Western]",Leonardo DiCaprio,The Quick and the Dead,69197,216.0,English,32000000.0,1995.0,6.4,0,Action,Thriller
2067,Jerry Zaks,45.0,12782508.0,[Drama],Leonardo DiCaprio,Marvin's Room,20163,71.0,English,23000000.0,1996.0,6.7,1000,Drama,Drama
2757,Baz Luhrmann,106.0,46338728.0,"[Drama, Romance]",Leonardo DiCaprio,Romeo + Juliet,167750,506.0,English,14500000.0,1996.0,6.8,10000,Drama,Romance
3476,Baz Luhrmann,490.0,144812796.0,"[Drama, Romance]",Leonardo DiCaprio,The Great Gatsby,362933,753.0,English,105000000.0,2013.0,7.3,115000,Drama,Romance

In [30]:
groupe_combined = Combined.groupby('actor_1_name')

groupe_combined.size()

actor_1_name
Brad Pitt            18
Leonardo DiCaprio    21
Meryl Streep         13
dtype: int64

# Project Results

## Summary of Findings

The analysis successfully identified:

- Top profitable movies
- IMDb Top 250 movies
- Highest-rated directors
- Popular genre combinations
- Critic and audience favourite actors

These insights demonstrate the effectiveness of Python for performing real-world exploratory data analysis.

# Conclusion

This project successfully demonstrates the complete workflow of data cleaning and exploratory data analysis using Python.

The movie dataset was cleaned by handling missing values, removing unnecessary columns, and eliminating duplicate records. Various analytical techniques were then applied to identify profitable movies, top-rated directors, successful genre combinations, and audience preferences.

The project highlights the importance of data preprocessing and exploratory analysis in extracting meaningful business insights from raw datasets.